Support DMA attributes in kernel versions after 4.6
Kernel commit "dma-mapping: use unsigned long for dma_attrs" changed the
"attrs" parameter of the dma_map_single_attrs() call. Make the code compatible
with both versions by checking whether DEFINE_DMA_ATTRS is defined.

This fixes compilation errors like these in kernel 4.9:
  error: implicit declaration of function 'DEFINE_DMA_ATTRS'